/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ControladorCrearPedido;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano
 */
public class CrearPedidos extends javax.swing.JFrame {
    public static final String BOTON_AGREGAR_EMPANADA = "boton agregar empanada";
    public static final String BOTON_AGREGAR_BEBIDA = "boton agregar bebida";
    public static final String BOTON_QUITAR_PRODUCTO = "boton quitar producto";
    public static final String BOTON_FINALIZAR_DETALLE = "boton finalizar detalle";
    private ArrayList<String[]> detalle;
    private DefaultTableModel tabla;
    /** Creates new form CrearPedidos */
    public CrearPedidos() {
        initComponents();
    }
    public void ejecutar(){
        this.setVisible(true);
        this.inicializarDetalle();
    }
    
    public void setControlador(ControladorCrearPedido control){
        botonAgregarEmpanada.setActionCommand(BOTON_AGREGAR_EMPANADA);
        botonAgregarEmpanada.addActionListener(control);
        botonAgregarBebida.setActionCommand(BOTON_AGREGAR_BEBIDA);
        botonAgregarBebida.addActionListener(control);
        botonQuitarProducto.setActionCommand(BOTON_QUITAR_PRODUCTO);
        botonQuitarProducto.addActionListener(control);
        botonConfirmarPedido.setActionCommand(BOTON_FINALIZAR_DETALLE);
        botonConfirmarPedido.addActionListener(control);
        
    }
    
    public void inicializarDetalle(){
        this.tabla = new DefaultTableModel();
        tabla.addColumn("Producto");
        tabla.addColumn("Cantidad/Volumen");
        tabla.addColumn("Subtotal");
        tabla.addColumn("Descuento");
        
        tablaDetalle.setModel(tabla);
    }
    
    public void actualizarDetalle(){
        this.tabla = new DefaultTableModel();
        tabla.addColumn("Producto");
        tabla.addColumn("Cantidad");
        tabla.addColumn("Subtotal");
        tabla.addColumn("Descuento");
        
        for(String[] fila : detalle){
            tabla.addRow(fila);
        }
        
        tablaDetalle.setModel(tabla);
    }

    public double getCampoTotal() {
        try {
        return Double.parseDouble(campoTotal.getText());    
        } catch (Exception e) {
            return 0;
        }
        
    }

    public void setCampoTotal(double campoTotal) {
        this.campoTotal.setText(""+campoTotal);
    }
    
    
    
    public void agregarFila(String[] fila){
        tabla.addRow(fila);
    }
    
    public void agregarEmpanadas (String[] empanadas){
        for (String empanada : empanadas) {
            desplegableTipoEmpanada.addItem(empanada);
        }
    }
    
    public int getCantidad () {
        try {
        return Integer.parseInt(campoCantidadEmpanada.getText());    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error al ingresar la cantidad");
        }
        return 0;
    }
    
    public String getEmpanada(){
        return desplegableTipoEmpanada.getSelectedItem().toString();
    }
    
    public String getBebida(){
        return desplegableBebidas.getSelectedItem().toString();
    }
    
    public String getVolumen(){
        String volumen = desplegableVolumen.getSelectedItem().toString();
        if("2L".equals(volumen))return "2";
        if("1.25L".equals(volumen))return "1.25";
        if("750.0ml".equals(volumen))return "0.75";
        if("500.0ml".equals(volumen))return "0.5";
        
        return null;
    }
    
    public void agregarBebidas (String[] bebidas){
        for (String bebida : bebidas) {
            desplegableBebidas.addItem(bebida);
        }
    }
    
    public int obtenerFilaSeleccionada(){
        return tablaDetalle.getSelectedRow();
    }
    
    public void eliminarFilaSeleccionada(int fila){
        tabla.removeRow(fila);
    }
    
    public String obtenerCantidadTabla(int fila){
        
        return tabla.getValueAt(fila, 1).toString();
    }
    
    public String obtenerNombreProductoTabla(int fila){
        
        return tabla.getValueAt(fila, 0).toString();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desplegableTipoEmpanada = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campoCantidadEmpanada = new javax.swing.JTextField();
        botonAgregarEmpanada = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        desplegableBebidas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        desplegableVolumen = new javax.swing.JComboBox<>();
        botonAgregarBebida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        botonQuitarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonConfirmarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Productos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empanada.png"))); // NOI18N

        jLabel3.setText("Empanadas");

        jLabel4.setText("cantidad");

        botonAgregarEmpanada.setText("Agregar Empanada");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebida.png"))); // NOI18N

        jLabel7.setText("bebida");

        jLabel8.setText("Volumen");

        botonAgregarBebida.setText("Agregar Bebida");

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        botonQuitarProducto.setText("Quitar Producto");

        jLabel9.setText("total");

        campoTotal.setEditable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonConfirmarPedido.setText("Confirmar Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonAgregarEmpanada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonAgregarBebida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(desplegableTipoEmpanada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(30, 30, 30)
                                                .addComponent(campoCantidadEmpanada)))
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(desplegableBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(desplegableVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonQuitarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConfirmarPedido)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(desplegableTipoEmpanada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(campoCantidadEmpanada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(desplegableBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(desplegableVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarEmpanada)
                    .addComponent(botonAgregarBebida))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonQuitarProducto)
                    .addComponent(jLabel9)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botonConfirmarPedido))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarBebida;
    private javax.swing.JButton botonAgregarEmpanada;
    private javax.swing.JButton botonConfirmarPedido;
    private javax.swing.JButton botonQuitarProducto;
    private javax.swing.JTextField campoCantidadEmpanada;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JComboBox<String> desplegableBebidas;
    private javax.swing.JComboBox<String> desplegableTipoEmpanada;
    private javax.swing.JComboBox<String> desplegableVolumen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables

    public void agregarVolumenes(String[] volumenes) {
        for (String volumen : volumenes) {
            if(Double.parseDouble(volumen) < 1){
                desplegableVolumen.addItem(Double.toString(Double.parseDouble(volumen)*1000) + "ml");
            }else{
                desplegableVolumen.addItem(volumen + "L");
            }
            
        }
    }

    public String obtenerProducto(int fila) {
        return tabla.getValueAt(fila,0).toString();
    }
    
    public double obtenerSubtotal(int fila) {
        return Double.parseDouble(tabla.getValueAt(fila,2).toString());
    }

}
